apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: analytics
data:
  DB_PATH: /data/db/app.db
  DB_TABLE: vehicles
  ARTIFACTS_ROOT: /data/artifacts
  RAW_DATA_ROOT: /data/raw
  CSV_SEPARATOR: ";"
  CSV_QUOTE_CHAR: '"'
  DATASET_URL: "https://data.gov.ua/dataset/0ffd8b75-0628-48cc-952a-9302f9799ec0/resource/3f13166f-090b-499e-8e23-e9851c5a5f67/download/reestrtz2026.zip"
